### ISSUE TITLE
Please Add a screenshot in Readme.md showing how round flags looks 

### ISSUE THREAD

**Issue by hansfpc** [pohodnya/react-native-round-flags#1]

**Comment by facuescobar** [comment]
You can access to Flags folders and see all images by yourself, they look great!

**Comment by hansfpc** [comment]
thanks

**Comment by facuescobar** [comment]
However, I think a Readme would be the best! 👍

**Comment by pohodnya** [comment]
@hansfpc, @facuescobar thanks! Good idea. I added a screenshot.
